// packages/tdp-editor/src/selectors/propSelectors/bindDataSelector.vue
<template>
    <div>
        <a-input prefix="{{" suffix="}}" v-model:value="bindData"></a-input>
    </div>
</template>
<script lang="ts">
import { defineComponent } from 'vue';
import type { IDesignerComponent, IPropsConfig } from 'tdp-editor-types/interface/designer';
export default defineComponent({
    name: EnumSelectorName.bindData,
});
</script>
<script lang="ts" setup>
import { EnumSelectorName } from 'tdp-editor-types/enum/designer';
import { EnumPropsValueType } from 'tdp-editor-types/enum/components';
import { usePropsProxy } from 'tdp-editor-utils/propsFactory';

const _props = defineProps<{
    element: IDesignerComponent;
    prop: IPropsConfig;
}>();
const bindData = usePropsProxy(
    _props.element,
    _props.prop.key as string,
    '',
    EnumPropsValueType.expression
);
</script>

// packages/tdp-editor/src/selectors/propSelectors/bindDataSelector.tsx
import { EnumSelectorName } from 'tdp-editor-types/enum/designer';
import type { TSelectorRender } from 'tdp-editor-types/interface/designer/selector';
import { EnumPropsValueType } from 'tdp-editor-types/enum/components';
import propsFactory from 'tdp-editor-utils/propsFactory';

export const name = EnumSelectorName.bindData;
export const render: TSelectorRender = (element, prop, options) => {
    return (
        <div>
            <a-input
                prefix="{{"
                suffix="}}"
                value={propsFactory.getPropsValue(element, prop.key)}
                onChange={(e: any) => {
                    propsFactory.setPropsValue(
                        element,
                        prop.key,
                        e.target.value,
                        EnumPropsValueType.expression
                    );
                }}
                onPressEnter={() => {
                    options.showParamsModal &&
                        options.showParamsModal(prop.key, EnumPropsValueType.expression);
                }}
            ></a-input>
        </div>
    );
};
