// packages/tdp-editor/src/components/selector/bindDataSelector.tsx
import { EnumPropsValueType } from 'tdp-editor-types/enum/components';
import type { IDesignerComponent, IPropsConfig } from 'tdp-editor-types/interface/designer';
import propsFactory from 'tdp-editor-utils/propsFactory';

export default function bindDataSelector(
    element: IDesignerComponent,
    props: IPropsConfig<{ k: any }>,
    other: {
        showParamsModal: (pmPropKey: string, pmPropValueType: EnumPropsValueType) => void;
    }
) {
    return (
        <div>
            <a-input
                prefix="{{"
                suffix="}}"
                value={propsFactory.getPropsValue(element, props.key)}
                onChange={(e: any) => {
                    propsFactory.setPropsValue(
                        element,
                        props.key,
                        e.target.value,
                        EnumPropsValueType.expression
                    );
                }}
                onPressEnter={() => {
                    other.showParamsModal(props.key, EnumPropsValueType.expression);
                }}
            ></a-input>
        </div>
    );
}

// packages/tdp-editor/src/selectors/propSelectors/bindDataSelector.vue
<template>
    <div>
        <a-input prefix="{{" suffix="}}" v-model:value="bindData"></a-input>
    </div>
</template>
<script lang="ts">
import { defineComponent } from 'vue';
import type { IDesignerComponent, IPropsConfig } from 'tdp-editor-types/interface/designer';
export default defineComponent({
    name: EnumSelectorName.bindData,
});
</script>
<script lang="ts" setup>
import { EnumSelectorName } from 'tdp-editor-types/enum/designer';
import { EnumPropsValueType } from 'tdp-editor-types/enum/components';
import { usePropsProxy } from 'tdp-editor-utils/propsFactory';

const _props = defineProps<{
    element: IDesignerComponent;
    prop: IPropsConfig;
}>();
const bindData = usePropsProxy(
    _props.element,
    _props.prop.key as string,
    '',
    EnumPropsValueType.expression
);
</script>
