// packages/tdp-editor/src/selectors/propSelectors/inputSelector.tsx
import { EnumSelectorName } from 'tdp-editor-types/enum/designer';
import type { TSelectorRender } from 'tdp-editor-types/interface/designer/selector';
import { EnumPropsValueType } from 'tdp-editor-types/enum/components';
import propsFactory from 'tdp-editor-utils/propsFactory';

export const name = EnumSelectorName.input;
export const render: TSelectorRender = (element, prop) => {
    return (
        <a-input
            value={propsFactory.getPropsValue(element, prop.key)}
            onChange={(e: any) => {
                propsFactory.setPropsValue(
                    element,
                    prop.key,
                    e.target.value,
                    EnumPropsValueType.string
                );
            }}
        ></a-input>
    );
};

// packages/tdp-editor/src/selectors/propSelectors/inputSelector.vue
<template>
    <a-input v-model:value="_value"></a-input>
</template>
<script lang="ts">
import { defineComponent } from 'vue';
export default defineComponent({
    name: EnumSelectorName.input,
});
</script>
<script lang="ts" setup>
import { computed } from 'vue';
import type { IDesignerComponent, IPropsConfig } from 'tdp-editor-types/interface/designer';
import { EnumSelectorName } from 'tdp-editor-types/enum/designer';
import { propsFactory } from 'tdp-editor-utils';
import { EnumPropsValueType } from 'tdp-editor-types/enum/components';

const _props = defineProps<{
    element: IDesignerComponent;
    prop: IPropsConfig;
}>();

const _value = computed<string>({
    get(): string {
        return propsFactory.getPropsValue(_props.element, _props.prop.key);
    },
    set(value: string) {
        propsFactory.setPropsValue(
            _props.element,
            _props.prop.key,
            value || '',
            EnumPropsValueType.string
        );
    },
});
const name = EnumSelectorName.input;
defineExpose({
    name,
});
</script>
