// packages/tdp-editor/src/components/selector/sliderSelector.tsx
import { EnumPropsValueType } from 'tdp-editor-types/enum/components';
import type { IDesignerComponent, IPropsConfig } from 'tdp-editor-types/interface/designer';
import propsFactory from 'tdp-editor-utils/propsFactory';

export default function sliderSelector(
    element: IDesignerComponent,
    props: IPropsConfig<{ k: any }>
) {
    return (
        <a-row>
            <a-col span={12}>
                <a-slider
                    value={propsFactory.getPropsValue(element, props.key)}
                    onChange={(value: string) =>
                        propsFactory.setPropsValue(
                            element,
                            props.key,
                            value,
                            EnumPropsValueType.number
                        )
                    }
                    min={props.sliderMin}
                    max={props.sliderMax}
                />
            </a-col>
            <a-col span={6}>
                <a-input-number
                    value={propsFactory.getPropsValue(element, props.key)}
                    onChange={(value: string) =>
                        propsFactory.setPropsValue(
                            element,
                            props.key,
                            value,
                            EnumPropsValueType.number
                        )
                    }
                    min={props.sliderMin}
                    max={props.sliderMax}
                    style="marginLeft: 5px"
                />
            </a-col>
        </a-row>
    );
}

// packages/tdp-editor/src/selectors/propSelectors/sliderSelector.vue
<template>
    <a-row>
        <a-col :span="12">
            <a-slider v-model:value="sliderValue" :min="min" :max="max" />
        </a-col>
        <a-col :span="6">
            <a-input-number
                v-model:value="sliderValue"
                :min="min"
                :max="max"
                style="marginleft: 5px"
            />
        </a-col>
    </a-row>
</template>
<script lang="ts">
import { defineComponent } from 'vue';
export default defineComponent({
    name: EnumSelectorName.slider,
});
</script>
<script lang="ts" setup>
import { computed } from 'vue';
import type { IDesignerComponent, IPropsConfig } from 'tdp-editor-types/interface/designer';
import type { ISelectorSliderOptions } from 'tdp-editor-types/interface/designer/selector';
import { EnumSelectorName } from 'tdp-editor-types/enum/designer';
import { usePropsProxy } from 'tdp-editor-utils/propsFactory';
import { EnumPropsValueType } from 'tdp-editor-types/enum/components';

const _props = defineProps<{
    element: IDesignerComponent;
    prop: IPropsConfig;
    options?: ISelectorSliderOptions;
}>();

const min = computed(() => {
    return _props.options?.min || 1;
});
const max = computed(() => {
    return _props.options?.max || 20;
});

const sliderValue = usePropsProxy(
    _props.element,
    _props.prop.key as string,
    min.value,
    EnumPropsValueType.number
);
</script>
