// packages/tdp-editor/src/selectors/propSelectors/switchSelector.tsx
import { EnumSelectorName } from 'tdp-editor-types/enum/designer';
import type { TSelectorRender } from 'tdp-editor-types/interface/designer/selector';
import { EnumPropsValueType } from 'tdp-editor-types/enum/components';
import propsFactory from 'tdp-editor-utils/propsFactory';

export const name = EnumSelectorName.switch;
export const render: TSelectorRender = (element, prop) => {
    return (
        <a-switch
            checked={propsFactory.getPropsValue(element, prop.key)}
            onChange={(checked: boolean) => {
                propsFactory.setPropsValue(element, prop.key, checked, EnumPropsValueType.boolean);
            }}
        />
    );
};

// packages/tdp-editor/src/selectors/propSelectors/switchSelector.vue
<template>
    <a-switch v-model:checked="switchValue" />
</template>
<script lang="ts">
import { defineComponent } from 'vue';
export default defineComponent({
    name: EnumSelectorName.switch,
});
</script>
<script lang="ts" setup>
import type { IDesignerComponent, IPropsConfig } from 'tdp-editor-types/interface/designer';
import { EnumSelectorName } from 'tdp-editor-types/enum/designer';
import { EnumPropsValueType } from 'tdp-editor-types/enum/components';
import { usePropsProxy } from 'tdp-editor-utils/propsFactory';

const _props = defineProps<{
    element: IDesignerComponent;
    prop: IPropsConfig;
}>();

const switchValue = usePropsProxy(
    _props.element,
    _props.prop.key as string,
    false,
    EnumPropsValueType.boolean
);
</script>
